// Comprehensive phrase library for Talk practice with difficulty levels

export type DifficultyLevel = 'beginner' | 'basic' | 'intermediate' | 'advanced';

export interface PhraseData {
  key: string;
  en: string;
  level: DifficultyLevel;
}

export interface CategoryData {
  id: string;
  title: string;
  icon: string;
  phrases: PhraseData[];
}

// Adult phrase library - comprehensive with difficulty levels
export const ADULT_PHRASE_LIBRARY: CategoryData[] = [
  {
    id: 'greetings',
    title: 'Greetings',
    icon: '👋',
    phrases: [
      { key: 'hello', en: 'Hello', level: 'beginner' },
      { key: 'good_morning', en: 'Good morning', level: 'beginner' },
      { key: 'good_night', en: 'Good night', level: 'beginner' },
      { key: 'goodbye', en: 'Goodbye', level: 'beginner' },
      { key: 'how_are_you', en: 'How are you?', level: 'basic' },
      { key: 'im_fine', en: 'I am fine', level: 'basic' },
      { key: 'nice_to_meet_you', en: 'Nice to meet you', level: 'basic' },
      { key: 'see_you_later', en: 'See you later', level: 'intermediate' },
      { key: 'have_a_nice_day', en: 'Have a nice day', level: 'intermediate' },
      { key: 'long_time_no_see', en: 'Long time no see', level: 'advanced' },
    ]
  },
  {
    id: 'basics',
    title: 'Basic Phrases',
    icon: '💬',
    phrases: [
      { key: 'yes', en: 'Yes', level: 'beginner' },
      { key: 'no', en: 'No', level: 'beginner' },
      { key: 'please', en: 'Please', level: 'beginner' },
      { key: 'thank_you', en: 'Thank you', level: 'beginner' },
      { key: 'excuse_me', en: 'Excuse me', level: 'basic' },
      { key: 'sorry', en: 'Sorry', level: 'basic' },
      { key: 'i_dont_understand', en: "I don't understand", level: 'basic' },
      { key: 'can_you_repeat', en: 'Can you repeat that?', level: 'intermediate' },
      { key: 'speak_slowly', en: 'Please speak slowly', level: 'intermediate' },
      { key: 'what_does_mean', en: 'What does that mean?', level: 'advanced' },
    ]
  },
  {
    id: 'introductions',
    title: 'Introductions',
    icon: '🤝',
    phrases: [
      { key: 'my_name_is', en: 'My name is...', level: 'beginner' },
      { key: 'whats_your_name', en: 'What is your name?', level: 'beginner' },
      { key: 'nice_to_meet_you', en: 'Nice to meet you', level: 'basic' },
      { key: 'where_from', en: 'Where are you from?', level: 'basic' },
      { key: 'i_am_from', en: 'I am from...', level: 'basic' },
      { key: 'what_do_you_do', en: 'What do you do?', level: 'intermediate' },
      { key: 'i_work_as', en: 'I work as...', level: 'intermediate' },
      { key: 'pleasure_meeting', en: 'It was a pleasure meeting you', level: 'advanced' },
    ]
  },
  {
    id: 'essentials',
    title: 'Essentials',
    icon: '🍽️',
    phrases: [
      { key: 'water', en: 'Water', level: 'beginner' },
      { key: 'food', en: 'Food', level: 'beginner' },
      { key: 'help', en: 'Help', level: 'beginner' },
      { key: 'how_much', en: 'How much?', level: 'basic' },
      { key: 'where_is', en: 'Where is...?', level: 'basic' },
      { key: 'i_need', en: 'I need...', level: 'basic' },
      { key: 'can_i_have', en: 'Can I have...?', level: 'intermediate' },
      { key: 'the_bill_please', en: 'The bill, please', level: 'intermediate' },
      { key: 'is_there_wifi', en: 'Is there WiFi?', level: 'intermediate' },
      { key: 'do_you_accept_cards', en: 'Do you accept cards?', level: 'advanced' },
    ]
  },
  {
    id: 'directions',
    title: 'Directions',
    icon: '🗺️',
    phrases: [
      { key: 'left', en: 'Left', level: 'beginner' },
      { key: 'right', en: 'Right', level: 'beginner' },
      { key: 'straight', en: 'Straight ahead', level: 'beginner' },
      { key: 'where_is_bathroom', en: 'Where is the bathroom?', level: 'basic' },
      { key: 'where_is_station', en: 'Where is the station?', level: 'basic' },
      { key: 'how_do_i_get_to', en: 'How do I get to...?', level: 'intermediate' },
      { key: 'is_it_far', en: 'Is it far from here?', level: 'intermediate' },
      { key: 'can_you_show_map', en: 'Can you show me on the map?', level: 'advanced' },
    ]
  },
  {
    id: 'shopping',
    title: 'Shopping',
    icon: '🛍️',
    phrases: [
      { key: 'how_much', en: 'How much is this?', level: 'beginner' },
      { key: 'too_expensive', en: 'Too expensive', level: 'basic' },
      { key: 'i_want_to_buy', en: 'I want to buy...', level: 'basic' },
      { key: 'do_you_have', en: 'Do you have...?', level: 'basic' },
      { key: 'different_size', en: 'Do you have a different size?', level: 'intermediate' },
      { key: 'can_i_try', en: 'Can I try this on?', level: 'intermediate' },
      { key: 'ill_take_it', en: "I'll take it", level: 'intermediate' },
      { key: 'can_you_discount', en: 'Can you give me a discount?', level: 'advanced' },
    ]
  },
  {
    id: 'restaurant',
    title: 'Restaurant',
    icon: '🍴',
    phrases: [
      { key: 'menu_please', en: 'Menu, please', level: 'beginner' },
      { key: 'i_would_like', en: 'I would like...', level: 'basic' },
      { key: 'what_recommend', en: 'What do you recommend?', level: 'basic' },
      { key: 'vegetarian', en: 'I am vegetarian', level: 'basic' },
      { key: 'allergic_to', en: 'I am allergic to...', level: 'intermediate' },
      { key: 'more_water', en: 'More water, please', level: 'intermediate' },
      { key: 'delicious', en: 'It was delicious', level: 'intermediate' },
      { key: 'reservation_for', en: 'I have a reservation for...', level: 'advanced' },
    ]
  },
  {
    id: 'travel',
    title: 'Travel',
    icon: '✈️',
    phrases: [
      { key: 'ticket_please', en: 'One ticket, please', level: 'beginner' },
      { key: 'what_time', en: 'What time?', level: 'beginner' },
      { key: 'where_is_airport', en: 'Where is the airport?', level: 'basic' },
      { key: 'i_have_reservation', en: 'I have a reservation', level: 'basic' },
      { key: 'what_time_leave', en: 'What time does it leave?', level: 'intermediate' },
      { key: 'delayed', en: 'Is it delayed?', level: 'intermediate' },
      { key: 'lost_luggage', en: 'I lost my luggage', level: 'advanced' },
      { key: 'missed_flight', en: 'I missed my flight', level: 'advanced' },
    ]
  },
  {
    id: 'emergency',
    title: 'Emergency',
    icon: '🚨',
    phrases: [
      { key: 'help', en: 'Help!', level: 'beginner' },
      { key: 'call_police', en: 'Call the police', level: 'basic' },
      { key: 'call_ambulance', en: 'Call an ambulance', level: 'basic' },
      { key: 'i_am_lost', en: 'I am lost', level: 'basic' },
      { key: 'need_doctor', en: 'I need a doctor', level: 'intermediate' },
      { key: 'not_feeling_well', en: 'I am not feeling well', level: 'intermediate' },
      { key: 'stolen', en: 'Someone stole my...', level: 'advanced' },
      { key: 'embassy', en: 'Where is the embassy?', level: 'advanced' },
    ]
  },
  {
    id: 'numbers',
    title: 'Numbers',
    icon: '🔢',
    phrases: [
      { key: 'zero', en: 'Zero', level: 'beginner' },
      { key: 'one', en: 'One', level: 'beginner' },
      { key: 'two', en: 'Two', level: 'beginner' },
      { key: 'three', en: 'Three', level: 'beginner' },
      { key: 'four', en: 'Four', level: 'beginner' },
      { key: 'five', en: 'Five', level: 'beginner' },
      { key: 'six', en: 'Six', level: 'beginner' },
      { key: 'seven', en: 'Seven', level: 'beginner' },
      { key: 'eight', en: 'Eight', level: 'beginner' },
      { key: 'nine', en: 'Nine', level: 'beginner' },
      { key: 'ten', en: 'Ten', level: 'beginner' },
      { key: 'eleven', en: 'Eleven', level: 'basic' },
      { key: 'twelve', en: 'Twelve', level: 'basic' },
      { key: 'thirteen', en: 'Thirteen', level: 'basic' },
      { key: 'fourteen', en: 'Fourteen', level: 'basic' },
      { key: 'fifteen', en: 'Fifteen', level: 'basic' },
      { key: 'sixteen', en: 'Sixteen', level: 'basic' },
      { key: 'seventeen', en: 'Seventeen', level: 'basic' },
      { key: 'eighteen', en: 'Eighteen', level: 'basic' },
      { key: 'nineteen', en: 'Nineteen', level: 'basic' },
      { key: 'twenty', en: 'Twenty', level: 'basic' },
      { key: 'thirty', en: 'Thirty', level: 'intermediate' },
      { key: 'forty', en: 'Forty', level: 'intermediate' },
      { key: 'fifty', en: 'Fifty', level: 'intermediate' },
      { key: 'sixty', en: 'Sixty', level: 'intermediate' },
      { key: 'seventy', en: 'Seventy', level: 'intermediate' },
      { key: 'eighty', en: 'Eighty', level: 'intermediate' },
      { key: 'ninety', en: 'Ninety', level: 'intermediate' },
      { key: 'hundred', en: 'One hundred', level: 'intermediate' },
      { key: 'two_hundred', en: 'Two hundred', level: 'advanced' },
      { key: 'five_hundred', en: 'Five hundred', level: 'advanced' },
      { key: 'thousand', en: 'One thousand', level: 'advanced' },
      { key: 'first', en: 'First', level: 'intermediate' },
      { key: 'second', en: 'Second', level: 'intermediate' },
      { key: 'third', en: 'Third', level: 'intermediate' },
      { key: 'how_much_cost', en: 'How much does it cost?', level: 'basic' },
      { key: 'it_costs_ten', en: 'It costs ten dollars', level: 'intermediate' },
      { key: 'phone_number', en: 'What is your phone number?', level: 'intermediate' },
      { key: 'my_number_is', en: 'My number is...', level: 'advanced' },
    ]
  },
  {
    id: 'time',
    title: 'Time',
    icon: '⏰',
    phrases: [
      { key: 'today', en: 'Today', level: 'beginner' },
      { key: 'tomorrow', en: 'Tomorrow', level: 'beginner' },
      { key: 'yesterday', en: 'Yesterday', level: 'beginner' },
      { key: 'what_time', en: 'What time is it?', level: 'basic' },
      { key: 'morning', en: 'In the morning', level: 'basic' },
      { key: 'afternoon', en: 'In the afternoon', level: 'basic' },
      { key: 'at_what_time', en: 'At what time?', level: 'intermediate' },
      { key: 'next_week', en: 'Next week', level: 'intermediate' },
    ]
  },
  {
    id: 'weather',
    title: 'Weather',
    icon: '🌤️',
    phrases: [
      { key: 'sunny', en: 'It is sunny', level: 'beginner' },
      { key: 'raining', en: 'It is raining', level: 'beginner' },
      { key: 'cold', en: 'It is cold', level: 'beginner' },
      { key: 'hot', en: 'It is hot', level: 'beginner' },
      { key: 'weather_today', en: 'How is the weather today?', level: 'basic' },
      { key: 'will_rain', en: 'Will it rain tomorrow?', level: 'intermediate' },
      { key: 'forecast', en: 'What is the forecast?', level: 'advanced' },
    ]
  },
];

// Kids phrase library - simplified and fun
export const KIDS_PHRASE_LIBRARY: CategoryData[] = [
  {
    id: 'greetings',
    title: 'Say Hi! 👋',
    icon: '👋',
    phrases: [
      { key: 'hello', en: 'Hello!', level: 'beginner' },
      { key: 'good_morning', en: 'Good morning!', level: 'beginner' },
      { key: 'goodbye', en: 'Bye bye!', level: 'beginner' },
      { key: 'how_are_you', en: 'How are you?', level: 'basic' },
      { key: 'im_fine', en: 'I am fine!', level: 'basic' },
    ]
  },
  {
    id: 'polite',
    title: 'Magic Words ✨',
    icon: '✨',
    phrases: [
      { key: 'please', en: 'Please', level: 'beginner' },
      { key: 'thank_you', en: 'Thank you!', level: 'beginner' },
      { key: 'sorry', en: 'Sorry', level: 'beginner' },
      { key: 'excuse_me', en: 'Excuse me', level: 'basic' },
      { key: 'youre_welcome', en: "You're welcome", level: 'basic' },
    ]
  },
  {
    id: 'basics',
    title: 'Yes & No 👍',
    icon: '👍',
    phrases: [
      { key: 'yes', en: 'Yes!', level: 'beginner' },
      { key: 'no', en: 'No', level: 'beginner' },
      { key: 'i_dont_know', en: "I don't know", level: 'basic' },
      { key: 'help', en: 'Help!', level: 'beginner' },
    ]
  },
  {
    id: 'food',
    title: 'Yummy! 🍎',
    icon: '🍎',
    phrases: [
      { key: 'water', en: 'Water', level: 'beginner' },
      { key: 'food', en: 'Food', level: 'beginner' },
      { key: 'hungry', en: 'I am hungry', level: 'basic' },
      { key: 'thirsty', en: 'I am thirsty', level: 'basic' },
      { key: 'delicious', en: 'Delicious!', level: 'basic' },
    ]
  },
  {
    id: 'family',
    title: 'My Family 👨‍👩‍👧',
    icon: '👨‍👩‍👧',
    phrases: [
      { key: 'mom', en: 'Mom', level: 'beginner' },
      { key: 'dad', en: 'Dad', level: 'beginner' },
      { key: 'brother', en: 'Brother', level: 'beginner' },
      { key: 'sister', en: 'Sister', level: 'beginner' },
      { key: 'i_love_you', en: 'I love you', level: 'basic' },
    ]
  },
  {
    id: 'animals',
    title: 'Animals 🐶',
    icon: '🐶',
    phrases: [
      { key: 'dog', en: 'Dog', level: 'beginner' },
      { key: 'cat', en: 'Cat', level: 'beginner' },
      { key: 'bird', en: 'Bird', level: 'beginner' },
      { key: 'fish', en: 'Fish', level: 'beginner' },
      { key: 'i_have_pet', en: 'I have a pet', level: 'basic' },
    ]
  },
  {
    id: 'colors',
    title: 'Colors 🌈',
    icon: '🌈',
    phrases: [
      { key: 'red', en: 'Red', level: 'beginner' },
      { key: 'blue', en: 'Blue', level: 'beginner' },
      { key: 'green', en: 'Green', level: 'beginner' },
      { key: 'yellow', en: 'Yellow', level: 'beginner' },
      { key: 'favorite_color', en: 'My favorite color is...', level: 'basic' },
    ]
  },
  {
    id: 'numbers',
    title: 'Count! 🔢',
    icon: '🔢',
    phrases: [
      { key: 'one', en: 'One', level: 'beginner' },
      { key: 'two', en: 'Two', level: 'beginner' },
      { key: 'three', en: 'Three', level: 'beginner' },
      { key: 'four', en: 'Four', level: 'beginner' },
      { key: 'five', en: 'Five', level: 'beginner' },
    ]
  },
];

// Extended translations for new phrases (add to LANGUAGE_CONTENT)
export const EXTENDED_TRANSLATIONS: Record<string, Record<string, string>> = {
  es: {
    see_you_later: 'Hasta luego',
    have_a_nice_day: 'Que tengas un buen día',
    long_time_no_see: 'Cuánto tiempo sin verte',
    can_you_repeat: '¿Puede repetir eso?',
    speak_slowly: 'Por favor, hable despacio',
    what_does_mean: '¿Qué significa eso?',
    whats_your_name: '¿Cómo te llamas?',
    where_from: '¿De dónde eres?',
    i_am_from: 'Soy de...',
    what_do_you_do: '¿A qué te dedicas?',
    i_work_as: 'Trabajo como...',
    pleasure_meeting: 'Fue un placer conocerte',
    i_need: 'Necesito...',
    can_i_have: '¿Puedo tener...?',
    the_bill_please: 'La cuenta, por favor',
    is_there_wifi: '¿Hay WiFi?',
    do_you_accept_cards: '¿Aceptan tarjetas?',
    left: 'Izquierda',
    right: 'Derecha',
    straight: 'Todo recto',
    where_is_bathroom: '¿Dónde está el baño?',
    where_is_station: '¿Dónde está la estación?',
    how_do_i_get_to: '¿Cómo llego a...?',
    is_it_far: '¿Está lejos de aquí?',
    can_you_show_map: '¿Puede mostrarme en el mapa?',
    too_expensive: 'Muy caro',
    i_want_to_buy: 'Quiero comprar...',
    do_you_have: '¿Tiene...?',
    different_size: '¿Tiene otra talla?',
    can_i_try: '¿Puedo probármelo?',
    ill_take_it: 'Me lo llevo',
    can_you_discount: '¿Puede hacerme un descuento?',
    menu_please: 'El menú, por favor',
    i_would_like: 'Me gustaría...',
    what_recommend: '¿Qué recomienda?',
    vegetarian: 'Soy vegetariano',
    allergic_to: 'Soy alérgico a...',
    more_water: 'Más agua, por favor',
    delicious: 'Estaba delicioso',
    reservation_for: 'Tengo una reserva para...',
    ticket_please: 'Un billete, por favor',
    what_time: '¿A qué hora?',
    where_is_airport: '¿Dónde está el aeropuerto?',
    i_have_reservation: 'Tengo una reserva',
    what_time_leave: '¿A qué hora sale?',
    delayed: '¿Está retrasado?',
    lost_luggage: 'Perdí mi equipaje',
    missed_flight: 'Perdí mi vuelo',
    call_police: 'Llame a la policía',
    call_ambulance: 'Llame una ambulancia',
    i_am_lost: 'Estoy perdido',
    need_doctor: 'Necesito un médico',
    not_feeling_well: 'No me siento bien',
    stolen: 'Me robaron mi...',
    embassy: '¿Dónde está la embajada?',
    zero: 'Cero',
    one: 'Uno',
    two: 'Dos',
    three: 'Tres',
    four: 'Cuatro',
    five: 'Cinco',
    six: 'Seis',
    seven: 'Siete',
    eight: 'Ocho',
    nine: 'Nueve',
    ten: 'Diez',
    eleven: 'Once',
    twelve: 'Doce',
    thirteen: 'Trece',
    fourteen: 'Catorce',
    fifteen: 'Quince',
    sixteen: 'Dieciséis',
    seventeen: 'Diecisiete',
    eighteen: 'Dieciocho',
    nineteen: 'Diecinueve',
    twenty: 'Veinte',
    thirty: 'Treinta',
    forty: 'Cuarenta',
    fifty: 'Cincuenta',
    sixty: 'Sesenta',
    seventy: 'Setenta',
    eighty: 'Ochenta',
    ninety: 'Noventa',
    hundred: 'Cien',
    two_hundred: 'Doscientos',
    five_hundred: 'Quinientos',
    thousand: 'Mil',
    first: 'Primero',
    second: 'Segundo',
    third: 'Tercero',
    how_much_cost: '¿Cuánto cuesta?',
    it_costs_ten: 'Cuesta diez dólares',
    phone_number: '¿Cuál es tu número de teléfono?',
    my_number_is: 'Mi número es...',
    today: 'Hoy',
    tomorrow: 'Mañana',
    yesterday: 'Ayer',
    morning: 'Por la mañana',
    afternoon: 'Por la tarde',
    at_what_time: '¿A qué hora?',
    next_week: 'La próxima semana',
    sunny: 'Hace sol',
    raining: 'Está lloviendo',
    cold: 'Hace frío',
    hot: 'Hace calor',
    weather_today: '¿Cómo está el clima hoy?',
    will_rain: '¿Lloverá mañana?',
    forecast: '¿Cuál es el pronóstico?',
    youre_welcome: 'De nada',
    i_dont_know: 'No sé',
    hungry: 'Tengo hambre',
    thirsty: 'Tengo sed',
    mom: 'Mamá',
    dad: 'Papá',
    brother: 'Hermano',
    sister: 'Hermana',
    i_love_you: 'Te quiero',
    dog: 'Perro',
    cat: 'Gato',
    bird: 'Pájaro',
    fish: 'Pez',
    i_have_pet: 'Tengo una mascota',
    red: 'Rojo',
    blue: 'Azul',
    green: 'Verde',
    yellow: 'Amarillo',
    favorite_color: 'Mi color favorito es...',
  },
  fr: {
    see_you_later: 'À plus tard',
    have_a_nice_day: 'Bonne journée',
    long_time_no_see: 'Ça fait longtemps',
    can_you_repeat: 'Pouvez-vous répéter?',
    speak_slowly: 'Parlez lentement, s\'il vous plaît',
    what_does_mean: 'Qu\'est-ce que ça veut dire?',
    whats_your_name: 'Comment vous appelez-vous?',
    where_from: 'D\'où venez-vous?',
    i_am_from: 'Je viens de...',
    what_do_you_do: 'Que faites-vous dans la vie?',
    i_work_as: 'Je travaille comme...',
    pleasure_meeting: 'C\'était un plaisir de vous rencontrer',
    left: 'Gauche',
    right: 'Droite',
    straight: 'Tout droit',
    where_is_bathroom: 'Où sont les toilettes?',
    menu_please: 'Le menu, s\'il vous plaît',
    delicious: 'C\'était délicieux',
    zero: 'Zéro',
    one: 'Un',
    two: 'Deux',
    three: 'Trois',
    four: 'Quatre',
    five: 'Cinq',
    six: 'Six',
    seven: 'Sept',
    eight: 'Huit',
    nine: 'Neuf',
    ten: 'Dix',
    eleven: 'Onze',
    twelve: 'Douze',
    thirteen: 'Treize',
    fourteen: 'Quatorze',
    fifteen: 'Quinze',
    sixteen: 'Seize',
    seventeen: 'Dix-sept',
    eighteen: 'Dix-huit',
    nineteen: 'Dix-neuf',
    twenty: 'Vingt',
    thirty: 'Trente',
    forty: 'Quarante',
    fifty: 'Cinquante',
    sixty: 'Soixante',
    seventy: 'Soixante-dix',
    eighty: 'Quatre-vingts',
    ninety: 'Quatre-vingt-dix',
    hundred: 'Cent',
    two_hundred: 'Deux cents',
    five_hundred: 'Cinq cents',
    thousand: 'Mille',
    first: 'Premier',
    second: 'Deuxième',
    third: 'Troisième',
    how_much_cost: 'Combien ça coûte?',
    it_costs_ten: 'Ça coûte dix dollars',
    phone_number: 'Quel est votre numéro de téléphone?',
    my_number_is: 'Mon numéro est...',
    today: 'Aujourd\'hui',
    tomorrow: 'Demain',
    mom: 'Maman',
    dad: 'Papa',
    i_love_you: 'Je t\'aime',
    dog: 'Chien',
    cat: 'Chat',
    red: 'Rouge',
    blue: 'Bleu',
    green: 'Vert',
    yellow: 'Jaune',
  },
  de: {
    see_you_later: 'Bis später',
    have_a_nice_day: 'Schönen Tag noch',
    can_you_repeat: 'Können Sie das wiederholen?',
    speak_slowly: 'Bitte sprechen Sie langsam',
    whats_your_name: 'Wie heißen Sie?',
    where_from: 'Woher kommen Sie?',
    i_am_from: 'Ich komme aus...',
    left: 'Links',
    right: 'Rechts',
    straight: 'Geradeaus',
    where_is_bathroom: 'Wo ist die Toilette?',
    menu_please: 'Die Speisekarte, bitte',
    delicious: 'Es war köstlich',
    one: 'Eins',
    two: 'Zwei',
    three: 'Drei',
    today: 'Heute',
    tomorrow: 'Morgen',
    mom: 'Mama',
    dad: 'Papa',
    i_love_you: 'Ich liebe dich',
    dog: 'Hund',
    cat: 'Katze',
    red: 'Rot',
    blue: 'Blau',
    green: 'Grün',
    yellow: 'Gelb',
  },
  ja: {
    see_you_later: 'また後で',
    have_a_nice_day: '良い一日を',
    whats_your_name: 'お名前は何ですか？',
    where_from: 'どこから来ましたか？',
    i_am_from: '私は...から来ました',
    left: '左',
    right: '右',
    straight: 'まっすぐ',
    where_is_bathroom: 'トイレはどこですか？',
    menu_please: 'メニューをください',
    delicious: 'おいしかったです',
    one: '一',
    two: '二',
    three: '三',
    today: '今日',
    tomorrow: '明日',
    mom: 'お母さん',
    dad: 'お父さん',
    i_love_you: '愛してる',
    dog: '犬',
    cat: '猫',
    red: '赤',
    blue: '青',
    green: '緑',
    yellow: '黄色',
  },
};

export const DIFFICULTY_LEVELS: { value: DifficultyLevel; label: string; emoji: string }[] = [
  { value: 'beginner', label: 'Beginner', emoji: '🌱' },
  { value: 'basic', label: 'Basic', emoji: '📗' },
  { value: 'intermediate', label: 'Intermediate', emoji: '📘' },
  { value: 'advanced', label: 'Advanced', emoji: '🔥' },
];
